In [1]:
''' import numpy as np 
"""

one dimention array is called as vector and
 dimention are called as axes
"""

#a=array()

a.ndim
a.itemsize
a.nbytes

a.dtype #a = np.array([1, 2, 3], dtype=np.float64)

	#arr = np.array([1, 2, 3, 4], dtype='S')
"""

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

"""




# numpy zeros

a = np.zeros((2, 3),dtype=np.int32) # by default the dtype is float64
print(a)
 
# numpy ones

a = np.ones((2, 3, 2))

"""

c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

"""


#two dimention Array we pass a list of a list of integers to the array() function.
	#A two-dimensional array is also called a matrix.
b = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)




#three dimention #Note that a 3-D array is also called a tensor.


c = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
    ]
)




"""
To find the number of axes and the number of elements
 on each axis of an array, you use the shape property. For example:
a.ndim
a.shape

The shape property returns a tuple

The numpy arange() function creates a new numpy array with
 evenly spaced numbers between start (inclusive) and stop (exclusive)
 with a given step:
"""
 
a = np.arange(1, 10, 2, dtype=np.float64)
#c[1,3]
c[1:2:3,:]'''


' import numpy as np \n"""\n\none dimention array is called as vector and\n dimention are called as axes\n"""\n\n#a=array()\n\na.ndim\na.itemsize\na.nbytes\n\na.dtype #a = np.array([1, 2, 3], dtype=np.float64)\n\n\t#arr = np.array([1, 2, 3, 4], dtype=\'S\')\n"""\n\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n\n"""\n\n\n\n\n# numpy zeros\n\na = np.zeros((2, 3),dtype=np.int32) # by default the dtype is float64\nprint(a)\n \n# numpy ones\n\na = np.ones((2, 3, 2))\n\n"""\n\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n\n"""\n\n\n#two dimention Array we pass a list of a list of integers to the array() function.\n\t#A two-dimensional array is also called a matrix.\nb = np.array(\n    [\n        [1, 2, 3],\n        [4, 5, 6]\n    ]\n)\n\n\n\

In [2]:
import numpy as np

In [3]:
a=np.arange(1,10,0.1)#start stop step

In [4]:
a

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [5]:
a = np.linspace(1, 2, 8)#start stop n-number of element

In [6]:
a

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        ])

In [7]:
a.ndim;a.shape;a.nbytes;a.size

8

In [8]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
five_up = (a > 5)
print(five_up)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [9]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [10]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [11]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [12]:
b = np.nonzero(a[1] > 5) ##search element with some condition
print(b) 

(array([1, 2, 3], dtype=int64),)


In [13]:
e=np.eye(5)
f = np.nonzero(e == 1)
print(f)

(array([0, 1, 2, 3, 4], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))


In [14]:
b = np.nonzero(a > 5) ##search element with some condition
print(b) 
list_of_coordinates= zip(f[0],b[0], b[1])
for coord in list_of_coordinates:
    print(coord)

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64), array([1, 2, 3, 0, 1, 2, 3], dtype=int64))
(0, 1, 1)
(1, 1, 2)
(2, 1, 3)
(3, 2, 0)
(4, 2, 1)


<img src="numpy-array-indexing-2d-array.svg">

In [15]:
print(a)
print(np.max(a, axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]


<img src="numpy-array-indexing-3d-array.svg">

RAVEL & FLATTEN

In [16]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.ravel(a)
b[0]=0
print(a)
print(b)
a=np.array([[1,2],[3,4]])
b=a.flatten()
b[0]
print(a)
print(b)

[[0 2]
 [3 4]]
[0 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]


In [34]:
a1=np.arange(1,101).reshape(20,5)
print(a1)
# a[0:16,:] =a[19,4] =a[16,1:] =a[17,2:] =a[18,3:] = 0

a1[0:16]=0

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


In [1]:
#Unable to scrape data from Amazon, so using wikipedia
import requests
import pandas as pd
from bs4 import BeautifulSoup

url = 'https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_and_their_capitals_in_native_languages'
response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'lxml')
    #scraped_text = soup.prettify()
    table = soup.find('table', class_='wikitable') #here, soup.find() will get data for just A character, soup.find_all() will give a list of all the characters.

    if table:
        data_rows = []
        for row in table.find_all('tr')[1:]:
            cells = row.find_all('td')
            data_row = [cell.get_text(strip=True) for cell in cells]
            data_rows.append(data_row)
    
        header = table.find('tr')
        cells = header.find_all('th')
        header_row = [cell.get_text(strip=True) for cell in cells]
        df = pd.DataFrame(data_rows, columns=header_row)

C:\Users\HUDA\AppData\Local\Temp\ipykernel_21660\1391450101.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
