# Logic Building

In [2]:
# Reverse string 

org_string = "hello world"
reverse_str = org_string[::-1]
print(reverse_str)

dlrow olleh


In [4]:
# Palindrome 


def rev(string):
    return string[::-1]

def peli(string):
    return True if string==string[::-1] else False



In [11]:
num = 0
if num < 0:
    print("Entered number is negative")
else:
    if num > 0 :
        print("Entered number is positive")
    else:
        print("Zero")


Zero


In [13]:
year=int (input('enter a year'))

if (year % 400 == 0 ) or ( year % 4 == 0 and year % 100 != 0):
    print ( f'{year} is a leap year.')
else: 
     print ( f'{year} is not leap year.')  


2024 is a leap year.


In [14]:
a = lambda y: 2*y
a (2)


4

In [22]:
l = [1,2,3,4,5,6,7,8,9]
l.append(2) 
print(l)
l.insert(3,0)
print(l)
l.copy()
print(l)
l.reverse()
print(l)
l.remove(2)
print(l)
l.sort()
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 2]
[1, 2, 3, 0, 4, 5, 6, 7, 8, 9, 2]
[1, 2, 3, 0, 4, 5, 6, 7, 8, 9, 2]
[2, 9, 8, 7, 6, 5, 4, 0, 3, 2, 1]
[9, 8, 7, 6, 5, 4, 0, 3, 2, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [24]:
 #Dictionary 

Info = {
   "name": "John",
   "age": 25,
   "city": "London"
}
print(Info)

{'name': 'John', 'age': 25, 'city': 'London'}


In [25]:

Info = dict(name="Marry", age=20, city="Newyork")
print(Info)


{'name': 'Marry', 'age': 20, 'city': 'Newyork'}


In [26]:
# set 

Info = {'John', 25, 'London'}  
print(Info)


{'London', 'John', 25}


In [27]:
colors = set(('Red', 'Blue', 'Green')) 
print(colors)

{'Green', 'Blue', 'Red'}


In [21]:
def func():
    pass
def func(a):  
    pass
func(6)
func()

TypeError: func() missing 1 required positional argument: 'a'

In [1]:
# Multiple 

class A:
    def method_a(self):
        print("Method A")

class B:
    def method_b(self):
        print("Method B")

class C(A, B):
    def method_c(self):
        print("Method C")


my_instance = C()
my_instance.method_a()  
my_instance.method_b()  
my_instance.method_c()  


Method A
Method B
Method C


In [2]:
# Hierarchical

class Shape:
    def draw(self):
        print("Drawing a shape")

class Circle(Shape):
    def draw(self):
        print("Drawing a circle")

class Rectangle(Shape):
    def draw(self):
        print("Drawing a rectangle")

# Creating instances of Circle and Rectangle
my_circle = Circle()
my_rectangle = Rectangle()
my_circle.draw()      # Specific to Circle
my_rectangle.draw()   # Specific to Rectangle


Drawing a circle
Drawing a rectangle


In [4]:
# Slicing strings  python strings are immutable 

str='JPythonString'
str1='JPythonString'
print(id(str))
print(id(str1))
print(str[5])
print(str[0:3])   #string[start:end:steps]

            

2982960070832
2982960070832
o
JPy


# list and tuples are ordered where set and dictionary is unordered 

In [15]:
# LIST 

a=['hi',7,[4,5],7,0]
print(a[0])

#TUPLES adds spaces or any changes in list use only parenthesis()

b=(1,)
a.sort
a

hi


['hi', 7, [4, 5], 7, 0]

In [4]:
#num = int(input('Enter a Number'))
num = 0
if num<0:
    print('Entered Number is Negative')
else:
    if num>0:
        print('Entered Number is Positive')
    else:
        print('Entered Number is Zero')

#types
# a=2+3j
# print(type(a),a)

Entered Number is Negative


In [10]:
# Even and odd numbers 

num = int(input('Enter a Number'))

if num % 2 == 0:
    print('Entered Number is Even')
else:
    if num % 2 != 0:
        print('Entered Number is Odd')
    else:
        print('Entered Number is Zero')


Entered Number is Odd


In [18]:
#iterative statement  -- repeat it will only run on time

# while loop
print('Even Number')
i=1
while i < 6:
    print(i)
    i += 1
else:
     print("loop finished")

print()
print()

print('Odd number')
num = 2
while num < 12:
    print(num)
    num = num + 2
else:
     print("loop finished")


Even Number
1
2
3
4
5
loop finished


Odd number
2
4
6
8
10
loop finished


In [37]:
# Using for loop 

def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result


number = 5
result = factorial(number)
print(f"The factorial of {number} is {result}")


The factorial of 5 is 120


In [47]:
# using while loop 

def factorial(n):
    result = 1
    while n > 1:
      # 1 * = n
      result *= n
      n -= 1              
    return result

number = 5 
result = factorial(number)
print(factorial(number))
    

120


In [48]:
# using recursive 

def factorial(n):
   if n == 1:
      return 1
   else:
      return n * factorial(n - 1)
 
factorial(3)


6

In [2]:
t1 = (11, 22, [33, 44, 55], 66, 77)


t1_list = list(t1)
t1_list[2][1] = 444
update_tuple = tuple(t1_list)


print(update_tuple)

(11, 22, [33, 444, 55], 66, 77)


In [4]:
list1 = ["M", "na", "i", "Ke"]
list2 = ["y", "me", "s", "lly"]
list3 = []
for idx in range(len(list1)):
    list3.append(list1[idx]+list2[idx])
print(list3)

['My', 'name', 'is', 'Kelly']


In [6]:
# Given dictionary
dict = {
    'emp1': {'name': 'Jhon', 'salary': 75000},
    'emp2': {'name': 'Emma', 'salary': 80000},
    'emp3': {'name': 'Brad', 'salary': 500}
}

# Update Brad's salary to 85000
dict['emp3']['salary'] = 85000

# Print the modified dictionary
print(dict)


{'emp1': {'name': 'Jhon', 'salary': 75000}, 'emp2': {'name': 'Emma', 'salary': 80000}, 'emp3': {'name': 'Brad', 'salary': 85000}}


In [7]:
# Given sets
set1 = {10, 20, 30, 40, 50, 60, 70}
set2 = {40, 50, 60, 70, 80, 90}

# Calculate the symmetric difference using the ^ operator
result_set = set1 ^ set2

# Print the result
print("Elements present in Set A or B, but not both:", result_set)


Elements present in Set A or B, but not both: {10, 80, 20, 90, 30}


In [8]:
# Calculate the sum of the series up to n terms
n = 5
series_sum = 0
term = 2
for i in range(1, n + 1):
    series_sum += term
    term = term * 10 + 2
print(f"Sum of the series up to {n} terms: {series_sum}")


Sum of the series up to 5 terms: 24690


In [14]:
List1 = [12, 23, 34, 45, 56, 67, 78, 89, 90]
result = ["Even" if num % 2 == 0 else "Odd" for num in List1]
print(List1)
print(result)


[12, 23, 34, 45, 56, 67, 78, 89, 90]
['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even']


In [15]:
n=7



c=0



while(n):



    if(n>5):



        c=c+n-1



        n=n-1



    else:



        break



print(n)



print(c)

5
11


In [17]:
i=2



while(i>0):



    i=i-1
    print(i)

1
0


In [18]:
list1 = [3 , 2 , 5 , 6 , 0 , 7, 9]



sum = 0



sum1 = 0



for elem in list1:



    if (elem % 2 == 0):



        sum = sum + elem



        continue



    if (elem % 3 == 0):



        sum1 = sum1 + elem







print(sum , end=" ")



print(sum1)

8 12


In [24]:
x = "abcdef"



i = "i"



while i in x:



    print(i, end=" ")

print(x)


abcdef


In [25]:
def show_employee(name, age, salary=9000):
    print(f"Employee Name: {name}")
    print(f"Employee Age: {age}")
    print(f"Employee Salary: {salary}")

# Example usage with all values provided
show_employee("John Doe", 30, 12000)

# Example usage with salary missing (default value will be used)
show_employee("Jane Smith", 25)


Employee Name: John Doe
Employee Age: 30
Employee Salary: 12000
Employee Name: Jane Smith
Employee Age: 25
Employee Salary: 9000


In [26]:
def sum(start, end):
    if start > end:
        return 0
    else:
        return start + sum(start + 1, end)

# Example usage
start_number = 3
end_number = 7

result = sum(start_number, end_number)
print(f"Sum of numbers between {start_number} and {end_number}: {result}")


Sum of numbers between 3 and 7: 25


In [27]:

list1 = [1991, 1992, 1994, 1996, 1998, 2000, 2001, 2002, 2004]

# Calculate age using a lambda function
current_year = 2022  # Assuming the current year is 2022

age_list = list(map(lambda year: current_year - year, list1))


print("Age List:", age_list)



Age List: [31, 30, 28, 26, 24, 22, 21, 20, 18]


In [28]:
class Vehicle:
    # Class attribute with default value
    color = "White"

    # Constructor to initialize instance attributes
    def __init__(self, name, speed, mileage):
        self.name = name
        self.speed = speed
        self.mileage = mileage

    # Method to display vehicle information
    def display_info(self):
        print(f"Color: {self.color}, Vehicle name: {self.name}, Speed: {self.speed}, Mileage: {self.mileage}")

# Creating instances of the Vehicle class
school_bus = Vehicle(name="School Volvo", speed=180, mileage=12)
audi_q5 = Vehicle(name="Audi Q5", speed=240, mileage=18)

# Displaying information for each vehicle
school_bus.display_info()
audi_q5.display_info()


Color: White, Vehicle name: School Volvo, Speed: 180, Mileage: 12
Color: White, Vehicle name: Audi Q5, Speed: 240, Mileage: 18


In [29]:
def is_file_empty(file_path):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
            return not content.strip()  # Check if the content is empty or contains only whitespace
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")
        return False


file_path = 'hello.txt'  

if is_file_empty(file_path):
    print(f"The file '{file_path}' is empty.")
else:
    print(f"The file '{file_path}' is not empty.")


The file 'hello.txt' is not empty.


In [1]:
import re

search = "Hello, 123 world!"

# Search for individual digits
result_individual = re.findall(r'\d', search)
print("Individual digits:", result_individual)

# Search for sequences of digits
result_sequences = re.findall(r'\d+', search)
print("Digit sequences:", result_sequences)


Individual digits: ['1', '2', '3']
Digit sequences: ['123']


NUMPY PRACTICE

In [2]:
import numpy as np

a = np.zeros((2,3),dtype=np.int32)
print(a)

a1=np.ones((2,3,2))
a1



[[0 0 0]
 [0 0 0]]


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [2]:
# Regex 

import re

s = "Python 10:54 was 4 4.5 5.5released on October 04, 2021."
result = re.search('\d',s)
print(result)
                                           
print('Matched string:',result.group())
print('Starting position:', result.start())
print('Ending position:',result.end())
print('Positions:',result.span())

<re.Match object; span=(7, 8), match='1'>
Matched string: 1
Starting position: 7
Ending position: 8
Positions: (7, 8)
